import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { FlashcardItem } from '../src/types';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const jsonSource = path.join(rootDir, 'docs', 'reference', 'flashcards.json');
const practiceMdSource = path.join(rootDir, 'docs', '14-Practice', 'FLASHCARDS.md');
const targetFile = path.join(rootDir, 'src', 'data', 'flashcards.ts');

export function parsePracticeFlashcardsMd(content: string): FlashcardItem[] {
  const cards: FlashcardItem[] = [];
  const sections = content.split(/^##\s+/m).slice(1);

  let counter = 100;
  for (const section of sections) {
    const lines = section.trim().split('\n');
    const categoryRaw = lines[0].trim();
    if (categoryRaw.startsWith('🎯') || categoryRaw.startsWith('Table of Contents')) continue;

    let category = categoryRaw;
    if (/auto scaling|load balancing|compute/i.test(categoryRaw)) category = 'Compute';
    else if (/storage/i.test(categoryRaw)) category = 'Storage';
    else if (/database/i.test(categoryRaw)) category = 'Database';
    else if (/networking/i.test(categoryRaw)) category = 'Networking';
    else if (/monitoring|security/i.test(categoryRaw)) category = 'Security';
    else if (/analytics|machine learning/i.test(categoryRaw)) category = 'Analytics';
    else if (/migration/i.test(categoryRaw)) category = 'Migration';
    else if (/best practice/i.test(categoryRaw)) category = 'Architecture';

    const text = lines.slice(1).join('\n');
    const qaBlocks = text.split(/\*\*Q:\s*/i).slice(1);

    for (const block of qaBlocks) {
      const qEndIndex = block.indexOf('**');
      if (qEndIndex === -1) continue;

      const question = block.substring(0, qEndIndex).trim();
      const remainder = block.substring(qEndIndex + 2).trim();

      const aMatch = remainder.match(/^A:\s*([\s\S]+?)(?=(\*\*Q:|$|---))/i);
      if (!aMatch) continue;

      const answer = aMatch[1].trim();
      counter++;

      cards.push({
        id: `fc-md-${counter}`,
        category,
        title: question.length > 50 ? question.substring(0, 47) + '...' : question,
        front: question,
        back: answer,
        examTip: `Key SAA-C03 concept for ${category}.`,
        tags: [category],
      });
    }
  }

  return cards;
}

export function generateFlashcards() {
  let allCards: FlashcardItem[] = [];

  if (fs.existsSync(jsonSource)) {
    const rawJson = fs.readFileSync(jsonSource, 'utf-8');
    const jsonCards = JSON.parse(rawJson) as FlashcardItem[];
    allCards.push(...jsonCards);
  }

  if (fs.existsSync(practiceMdSource)) {
    const rawMd = fs.readFileSync(practiceMdSource, 'utf-8');
    const parsedMdCards = parsePracticeFlashcardsMd(rawMd);
    allCards.push(...parsedMdCards);
  }

  // Deduplicate by front question
  const seen = new Set<string>();
  const uniqueCards: FlashcardItem[] = [];
  for (const c of allCards) {
    const key = c.front.toLowerCase().replace(/[^\w]/g, '');
    if (!seen.has(key)) {
      seen.add(key);
      uniqueCards.push(c);
    }
  }

  const fileContent = `// -------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED by scripts/generate-flashcards.ts
// DO NOT EDIT MANUALLY. Source of truth is docs/reference/flashcards.json & docs/14-Practice/FLASHCARDS.md.
// Run "npm run data:generate" to re-generate this file.
// -------------------------------------------------------------------------

import { FlashcardItem } from '../types';

export const FLASHCARDS_DATA: FlashcardItem[] = ${JSON.stringify(uniqueCards, null, 2)};
`;

  fs.writeFileSync(targetFile, fileContent, 'utf-8');
  console.log(`✅ Successfully generated ${uniqueCards.length} flashcards in ${path.relative(rootDir, targetFile)}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateFlashcards();
}
