import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const sourceFile = path.join(rootDir, 'docs', 'reference', 'decision-matrices.json');
const targetFile = path.join(rootDir, 'src', 'data', 'decision-matrices.ts');

export function generateDecisionMatrices() {
  if (!fs.existsSync(sourceFile)) {
    throw new Error(`Source file ${sourceFile} does not exist.`);
  }

  const rawJson = fs.readFileSync(sourceFile, 'utf-8');
  const data = JSON.parse(rawJson);

  const fileContent = `// -------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED by scripts/generate-decision-matrices.ts
// DO NOT EDIT MANUALLY. Source of truth is docs/reference/decision-matrices.json.
// Run "npm run data:generate" to re-generate this file.
// -------------------------------------------------------------------------

import { DecisionMatrixCategory } from '../types';

export const DECISION_MATRICES: DecisionMatrixCategory[] = ${JSON.stringify(data, null, 2)};
`;

  fs.writeFileSync(targetFile, fileContent, 'utf-8');
  console.log(`✅ Successfully generated ${data.length} decision matrix categories in ${path.relative(rootDir, targetFile)}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateDecisionMatrices();
}
