import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const docsDir = path.join(rootDir, 'docs');
const targetFile = path.join(rootDir, 'src', 'data', 'modules-meta.ts');

interface ModuleMetaConfig {
  id: string;
  slug: string;
  number: number;
  title: string;
  domain: string;
  icon: string;
  examWeight: string;
  timeEstimates: {
    deepDive: string;
    fastLearn: string;
    ultraFast: string;
  };
  priority: 'CRITICAL' | 'HIGH' | 'MEDIUM';
}

const DOMAIN_MAP: Record<string, { domain: string; icon: string; priority: 'CRITICAL' | 'HIGH' | 'MEDIUM'; weight: string }> = {
  '01-AWS-Fundamentals': { domain: 'Fundamentals', icon: 'IconCloud', priority: 'CRITICAL', weight: '~10%' },
  '02-IAM': { domain: 'Security', icon: 'IconUserShield', priority: 'CRITICAL', weight: '~15-20%' },
  '03-Compute': { domain: 'Compute', icon: 'IconCpu', priority: 'CRITICAL', weight: '~20-25%' },
  '04-Storage': { domain: 'Storage', icon: 'IconArchive', priority: 'CRITICAL', weight: '~15-20%' },
  '05-Database': { domain: 'Database', icon: 'IconDatabase', priority: 'CRITICAL', weight: '~15-20%' },
  '06-Networking': { domain: 'Networking', icon: 'IconTopologyStar', priority: 'CRITICAL', weight: '~20-25%' },
  '07-Security': { domain: 'Security', icon: 'IconShieldLock', priority: 'CRITICAL', weight: '~20-25%' },
  '08-Application-Integration': { domain: 'Integration', icon: 'IconArrowsJoin', priority: 'HIGH', weight: '~10-15%' },
  '09-Monitoring': { domain: 'Management', icon: 'IconChartLine', priority: 'HIGH', weight: '~10-15%' },
  '10-Migration': { domain: 'Migration', icon: 'IconTruckDelivery', priority: 'MEDIUM', weight: '~8-12%' },
  '11-Analytics': { domain: 'Analytics', icon: 'IconChartHistogram', priority: 'MEDIUM', weight: '~8-12%' },
  '12-Architecture-Patterns': { domain: 'Architecture', icon: 'IconHierarchy3', priority: 'CRITICAL', weight: '~25-30%' },
  '13-Cost-Optimization': { domain: 'Cost', icon: 'IconCoin', priority: 'HIGH', weight: '~10-15%' },
  '14-Practice': { domain: 'Practice', icon: 'IconClipboardCheck', priority: 'CRITICAL', weight: 'Final Prep' },
};

export function generateModulesMeta() {
  const dirs = fs.readdirSync(docsDir, { withFileTypes: true })
    .filter(d => d.isDirectory() && /^\d{2}-/.test(d.name))
    .sort((a, b) => a.name.localeCompare(b.name));

  const modules: ModuleMetaConfig[] = [];

  for (const dir of dirs) {
    const modId = dir.name;
    const num = parseInt(modId.substring(0, 2), 10);
    const modPath = path.join(docsDir, modId);
    const readmePath = path.join(modPath, 'README.md');
    const fastLearnPath = path.join(modPath, 'FAST-LEARN.md');
    const ultraFastPath = path.join(modPath, 'ULTRA-FAST-LEARN.md');

    let title = modId.replace(/^\d{2}-/, '').replace(/-/g, ' ');
    if (fs.existsSync(readmePath)) {
      const readmeContent = fs.readFileSync(readmePath, 'utf-8');
      const titleMatch = readmeContent.match(/^#\s+(?:Module\s+\d+:\s*)?([^\n\r]+)/m);
      if (titleMatch) {
        title = titleMatch[1].trim();
      }
    }

    const mapping = DOMAIN_MAP[modId] || {
      domain: 'Fundamentals',
      icon: 'Globe',
      priority: 'MEDIUM' as const,
      weight: '~10%',
    };

    // Calculate reading time estimates based on word counts
    let deepDiveMin = 45;
    let fastLearnMin = 30;
    let ultraFastMin = 10;

    if (fs.existsSync(readmePath)) {
      const words = fs.readFileSync(readmePath, 'utf-8').split(/\s+/).length;
      deepDiveMin = Math.max(30, Math.min(90, Math.round(words / 120 / 5) * 5));
    }
    if (fs.existsSync(fastLearnPath)) {
      const words = fs.readFileSync(fastLearnPath, 'utf-8').split(/\s+/).length;
      fastLearnMin = Math.max(20, Math.min(60, Math.round(words / 100 / 5) * 5));
    }
    if (fs.existsSync(ultraFastPath)) {
      const words = fs.readFileSync(ultraFastPath, 'utf-8').split(/\s+/).length;
      ultraFastMin = Math.max(5, Math.min(25, Math.round(words / 80 / 5) * 5));
    }

    modules.push({
      id: modId,
      slug: modId.toLowerCase(),
      number: num,
      title: title,
      domain: mapping.domain,
      icon: mapping.icon,
      examWeight: mapping.weight,
      timeEstimates: {
        deepDive: `${deepDiveMin} min`,
        fastLearn: `${fastLearnMin} min`,
        ultraFast: `${ultraFastMin} min`,
      },
      priority: mapping.priority,
    });
  }

  const fileContent = `// -------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED by scripts/generate-modules-meta.ts
// DO NOT EDIT MANUALLY. Source of truth is in docs/ directory.
// Run "npm run data:generate" to re-generate this file.
// -------------------------------------------------------------------------

import { ModuleMeta } from '../types';

export const MODULES_METADATA: ModuleMeta[] = ${JSON.stringify(modules, null, 2)};
`;

  fs.writeFileSync(targetFile, fileContent, 'utf-8');
  console.log(`✅ Successfully generated ${modules.length} modules in ${path.relative(rootDir, targetFile)}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateModulesMeta();
}
