import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const docsDir = path.join(rootDir, 'docs');
const targetFile = path.join(rootDir, 'src', 'data', 'modules-content.ts');

export function generateModulesContent() {
  const contentMap: Record<string, string> = {};

  function scanDir(dir: string, baseRelative: string) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const relPath = path.join(baseRelative, entry.name).replace(/\\/g, '/');

      if (entry.isDirectory()) {
        scanDir(fullPath, relPath);
      } else if (entry.isFile() && entry.name.endsWith('.md')) {
        const text = fs.readFileSync(fullPath, 'utf-8');
        contentMap[relPath.toLowerCase()] = text;
      }
    }
  }

  scanDir(docsDir, '');

  const fileContent = `// -------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED by scripts/generate-modules-content.ts
// DO NOT EDIT MANUALLY. Source of truth is docs/**/*.md.
// Run "bun run data:generate" to re-generate this file.
// -------------------------------------------------------------------------

export const DOCS_CONTENT_MAP: Record<string, string> = ${JSON.stringify(contentMap, null, 2)};

export function getCompiledDocContent(relativePath: string): string {
  if (!relativePath) return '';
  const cleanPath = relativePath.replace(/^.*\\/docs\\//i, '').replace(/^\\/+/, '').toLowerCase();
  return DOCS_CONTENT_MAP[cleanPath] || '';
}
`;

  fs.writeFileSync(targetFile, fileContent, 'utf-8');
  console.log(`✅ Successfully compiled ${Object.keys(contentMap).length} markdown documents into ${path.relative(rootDir, targetFile)}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateModulesContent();
}
