import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const sourceFile = path.join(rootDir, 'docs', 'reference', 'architecture-patterns.json');
const targetFile = path.join(rootDir, 'src', 'data', 'architecture-patterns.ts');

export function generateArchitecturePatterns() {
  if (!fs.existsSync(sourceFile)) {
    throw new Error(`Source file ${sourceFile} does not exist.`);
  }

  const rawJson = fs.readFileSync(sourceFile, 'utf-8');
  const data = JSON.parse(rawJson);

  const fileContent = `// -------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED by scripts/generate-architecture-patterns.ts
// DO NOT EDIT MANUALLY. Source of truth is docs/reference/architecture-patterns.json.
// Run "bun run data:generate" to re-generate this file.
// -------------------------------------------------------------------------

import { ArchitecturePattern } from '../types';

export const ARCHITECTURE_PATTERNS: ArchitecturePattern[] = ${JSON.stringify(data, null, 2)};
`;

  fs.writeFileSync(targetFile, fileContent, 'utf-8');
  console.log(`✅ Successfully generated ${data.length} architecture patterns in ${path.relative(rootDir, targetFile)}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateArchitecturePatterns();
}
