// -------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED by scripts/generate-flashcards.ts
// DO NOT EDIT MANUALLY. Source of truth is docs/reference/flashcards.json & docs/14-Practice/FLASHCARDS.md.
// Run "npm run data:generate" to re-generate this file.
// -------------------------------------------------------------------------

import { FlashcardItem } from '../types';

export const FLASHCARDS_DATA: FlashcardItem[] = [
  {
    "id": "fc-1",
    "category": "Compute",
    "title": "Auto Scaling Cooldown Period",
    "front": "What is the purpose of a cooldown period in EC2 Auto Scaling?",
    "back": "Prevents rapid, unintended scaling events by suppressing additional scale-out/scale-in actions until the cooldown period ends, allowing metrics and new instances to stabilize.",
    "examTip": "Default cooldown is 300 seconds (5 minutes). Use target tracking or step scaling to reduce cooldown bottlenecks.",
    "tags": [
      "EC2",
      "Auto Scaling",
      "Compute"
    ]
  },
  {
    "id": "fc-2",
    "category": "Compute",
    "title": "ECS Dynamic Port Mapping",
    "front": "Which load balancers support dynamic host port mapping for ECS tasks on EC2 launch type?",
    "back": "Application Load Balancer (ALB) and Network Load Balancer (NLB). Multiple containers from the same task definition can run on the same EC2 instance using random dynamic host ports (port 0).",
    "examTip": "Classic Load Balancer does NOT support dynamic port mapping. Always choose ALB for ECS microservices.",
    "tags": [
      "ECS",
      "ALB",
      "Containers"
    ]
  },
  {
    "id": "fc-3",
    "category": "Compute",
    "title": "EC2 Spot Instances",
    "front": "When should you choose EC2 Spot Instances instead of On-Demand or Reserved?",
    "back": "For stateless, fault-tolerant, and flexible workloads (batch processing, data analysis, CI/CD worker nodes). Saves up to 90% off On-Demand pricing.",
    "examTip": "AWS can reclaim Spot instances with a 2-minute termination warning. NEVER use Spot for single-instance stateful databases.",
    "tags": [
      "EC2",
      "Spot",
      "Cost"
    ]
  },
  {
    "id": "fc-4",
    "category": "Compute",
    "title": "Lambda Execution Limits",
    "front": "What are the maximum timeout and temporary ephemeral storage (/tmp) limits for AWS Lambda?",
    "back": "Max Timeout: 15 minutes (900 seconds).\nEphemeral Storage (/tmp): 512 MB up to 10 GB.\nMemory: 128 MB up to 10,240 MB (10 GB).",
    "examTip": "For long-running tasks (>15 min), migrate to AWS Fargate, ECS, or AWS Step Functions orchestrating multiple Lambda executions.",
    "tags": [
      "Lambda",
      "Serverless",
      "Limits"
    ]
  },
  {
    "id": "fc-5",
    "category": "Storage",
    "title": "S3 Consistency Model",
    "front": "What is Amazon S3's data consistency model for new objects and updates?",
    "back": "Strong read-after-write consistency for all PUT, LIST, and DELETE operations of objects across all AWS Regions immediately after a successful upload.",
    "examTip": "Concurrent writes to the same key use 'last-write-wins' semantics.",
    "tags": [
      "S3",
      "Storage",
      "Consistency"
    ]
  },
  {
    "id": "fc-6",
    "category": "Storage",
    "title": "S3 Object Lock (WORM)",
    "front": "How do you achieve WORM (Write Once, Read Many) compliance to prevent object deletion or overwrite in S3?",
    "back": "Enable S3 Object Lock at bucket creation (requires S3 Versioning). Provides Governance Mode (override with specific IAM permission) and Compliance Mode (cannot be deleted by anyone, including root).",
    "examTip": "Compliance Mode meets strict regulatory retention requirements (SEC Rule 17a-4, FINRA).",
    "tags": [
      "S3",
      "Security",
      "Compliance"
    ]
  },
  {
    "id": "fc-7",
    "category": "Storage",
    "title": "S3 Presigned URLs vs Signed Cookies",
    "front": "What is the key architectural difference between S3 Presigned URLs and CloudFront Signed Cookies?",
    "back": "Presigned URLs grant temporary access to individual specific files via URL query parameters.\nSigned Cookies grant access to multiple premium/restricted files or entire directory paths without altering URL structure.",
    "examTip": "Use Signed URLs for single file downloads (e.g. invoice PDF). Use Signed Cookies for media streaming or downloading a package of multiple files.",
    "tags": [
      "S3",
      "CloudFront",
      "Security"
    ]
  },
  {
    "id": "fc-8",
    "category": "Storage",
    "title": "EFS vs EBS vs FSx for Windows",
    "front": "How do you choose between Amazon EBS, EFS, and FSx for Windows?",
    "back": "• EBS: Block storage locked to a single AZ for 1 EC2 instance.\n• EFS: Managed POSIX NFS shared file system across multiple AZs for Linux/containers.\n• FSx Windows: SMB protocol shared file system with Active Directory integration for Windows workloads.",
    "examTip": "EFS is Linux-only (NFS). If the scenario mentions Microsoft Active Directory, Windows ACLs, or SMB, the answer is always FSx for Windows.",
    "tags": [
      "EFS",
      "EBS",
      "FSx",
      "Storage"
    ]
  },
  {
    "id": "fc-9",
    "category": "Database",
    "title": "Aurora Multi-AZ vs Read Replicas",
    "front": "What is the difference between Amazon RDS Multi-AZ Standby and Read Replicas?",
    "back": "• Multi-AZ Standby: Synchronous replication to secondary AZ for Disaster Recovery (NOT readable, sub-60s automated failover).\n• Read Replicas: Asynchronous replication (up to 15 in Aurora, 5 in RDS) to offload read traffic (actively readable).",
    "examTip": "Aurora replicates 6 copies of data across 3 AZs automatically at storage layer and supports sub-30s failover to a Read Replica.",
    "tags": [
      "Aurora",
      "RDS",
      "Database",
      "HA"
    ]
  },
  {
    "id": "fc-10",
    "category": "Database",
    "title": "DynamoDB Scaling: On-Demand vs Provisioned",
    "front": "When should you choose DynamoDB On-Demand capacity mode over Provisioned mode?",
    "back": "Choose On-Demand for workloads with unknown, unpredictable, or highly spiky traffic where requests ramp from zero to thousands instantly (pay-per-request).\nChoose Provisioned (with Auto Scaling) for predictable, steady-state traffic to minimize cost.",
    "examTip": "On-Demand requires zero capacity planning and eliminates throttling for sudden traffic spikes.",
    "tags": [
      "DynamoDB",
      "NoSQL",
      "Database"
    ]
  },
  {
    "id": "fc-11",
    "category": "Database",
    "title": "DynamoDB Accelerator (DAX)",
    "front": "What is DynamoDB DAX and what latency profile does it provide?",
    "back": "DAX is a fully managed, highly available in-memory cache for Amazon DynamoDB that delivers microsecond response times (10x performance improvement from milliseconds to microseconds) for read-heavy workloads.",
    "examTip": "DAX is seamless and API-compatible: applications don't need code refactoring, just swap the SDK client.",
    "tags": [
      "DynamoDB",
      "DAX",
      "Caching"
    ]
  },
  {
    "id": "fc-12",
    "category": "Networking",
    "title": "VPC Gateway Endpoints vs Interface Endpoints",
    "front": "What services support free VPC Gateway Endpoints, and how do they differ from Interface Endpoints (PrivateLink)?",
    "back": "• Gateway Endpoints: Only support Amazon S3 and Amazon DynamoDB. Target is added to Route Tables (FREE of charge).\n• Interface Endpoints: Use AWS PrivateLink with an ENI and private IP inside your subnet. Charged hourly + data processing fee. Supports almost all other AWS services.",
    "examTip": "Gateway endpoints cannot be accessed from on-premises over Direct Connect / VPN without a proxy. Interface endpoints can.",
    "tags": [
      "VPC",
      "PrivateLink",
      "Networking"
    ]
  },
  {
    "id": "fc-13",
    "category": "Networking",
    "title": "Security Groups vs Network ACLs (NACL)",
    "front": "What are the fundamental differences between Security Groups and Network ACLs?",
    "back": "• Security Groups: Stateful (return traffic automatically allowed), operate at instance/ENI level, allow rules ONLY.\n• Network ACLs (NACL): Stateless (inbound and outbound rules evaluated separately), operate at Subnet level, support ALLOW and DENY rules in numbered order.",
    "examTip": "To block a specific abusive IP address or subnet CIDR, you MUST use a Network ACL (deny rule) or AWS WAF, as Security Groups do not have deny rules.",
    "tags": [
      "VPC",
      "Security",
      "NACL"
    ]
  },
  {
    "id": "fc-14",
    "category": "Networking",
    "title": "Route 53 Routing Policies",
    "front": "Explain Latency-based vs Geolocation vs Geoproximity routing in Route 53.",
    "back": "• Latency Routing: Routes traffic to the AWS region that provides the lowest network round-trip latency for the user.\n• Geolocation Routing: Routes traffic based on the geographic location of the DNS query origin (e.g. EU users -> EU server, US -> US).\n• Geoproximity Routing: Routes traffic based on geographic distance with a 'bias' slider to shrink or expand regional boundaries (requires Route 53 Traffic Flow).",
    "examTip": "Use Geolocation for legal compliance/language localization; use Latency Routing for maximum speed and performance.",
    "tags": [
      "Route 53",
      "DNS",
      "Networking"
    ]
  },
  {
    "id": "fc-15",
    "category": "Security",
    "title": "AWS KMS Key Types: AWS Managed vs Customer Managed (CMK)",
    "front": "What is the advantage of Customer Managed KMS Keys (CMK) over AWS Managed Keys?",
    "back": "Customer Managed Keys allow full control over Key Policies, IAM user access, automated annual rotation (or manual on-demand rotation), key deletion, and cross-account access. AWS Managed Keys cannot have their policies modified or be manually rotated.",
    "examTip": "If an exam question mentions auditing key usage, custom key policies, or cross-account KMS decryption, choose Customer Managed Key.",
    "tags": [
      "KMS",
      "Encryption",
      "Security"
    ]
  },
  {
    "id": "fc-16",
    "category": "Security",
    "title": "AWS Secrets Manager vs Parameter Store",
    "front": "When should you choose AWS Secrets Manager instead of Systems Manager Parameter Store?",
    "back": "Choose Secrets Manager when you need automatic credential rotation (built-in Lambda templates for RDS, Aurora, Redshift, DocumentDB) and generating random secrets.\nChoose Parameter Store (Standard tier is FREE) for simple plaintext or SecureString configuration parameters without rotation.",
    "examTip": "If automatic database password rotation is required, Secrets Manager is always the answer.",
    "tags": [
      "Secrets Manager",
      "Security",
      "Parameter Store"
    ]
  },
  {
    "id": "fc-17",
    "category": "Integration",
    "title": "SQS Standard vs SQS FIFO Queues",
    "front": "What are the trade-offs between SQS Standard and SQS FIFO Queues?",
    "back": "• SQS Standard: Virtually unlimited throughput, best-effort ordering, at-least-once delivery (duplicates possible).\n• SQS FIFO: Strict First-In-First-Out ordering, exactly-once processing (deduplication ID), limited to 300 msgs/sec (or 3,000 with batching / 70,000 in high throughput mode).",
    "examTip": "FIFO queue names MUST end with the `.fifo` suffix.",
    "tags": [
      "SQS",
      "Integration",
      "Messaging"
    ]
  },
  {
    "id": "fc-18",
    "category": "Integration",
    "title": "SNS Fanout Architecture",
    "front": "What is the SNS Fanout pattern and why is it used?",
    "back": "A message is published to a single SNS Topic and replicated immediately to multiple subscribing SQS queues simultaneously. This decouples event publishers from diverse asynchronous consumers (e.g. order processing -> billing queue, analytics queue, shipping queue).",
    "examTip": "SNS Fanout provides high availability and fault isolation: if one consumer worker goes down, other queues continue processing without interruption.",
    "tags": [
      "SNS",
      "SQS",
      "Fanout",
      "Architecture"
    ]
  },
  {
    "id": "fc-19",
    "category": "Monitoring",
    "title": "CloudWatch Metrics vs CloudTrail Logs",
    "front": "What is the core distinction between Amazon CloudWatch and AWS CloudTrail?",
    "back": "• CloudWatch: Performance and health monitoring (CPU utilization, disk I/O, network in/out, custom metrics, alarms, application logs).\n• CloudTrail: Governance, compliance, and auditing of API activity (who made which API call, from what IP, at what time).",
    "examTip": "CloudWatch = 'How are resources performing?'; CloudTrail = 'Who did what in the AWS account?'.",
    "tags": [
      "CloudWatch",
      "CloudTrail",
      "Monitoring"
    ]
  },
  {
    "id": "fc-20",
    "category": "Architecture",
    "title": "Disaster Recovery Strategies (RTO & RPO)",
    "front": "Rank the 4 AWS Disaster Recovery strategies from lowest cost / slowest RTO to highest cost / fastest RTO.",
    "back": "1. Backup & Restore (Hours/Days RTO/RPO - Lowest Cost)\n2. Pilot Light (Core DB replicated, compute scaled down - 10-30 min RTO)\n3. Warm Standby (Scaled-down active replica running 24/7 - Minutes RTO)\n4. Multi-Site Active-Active (Real-time live traffic in multiple regions - Zero RTO/RPO - Highest Cost)",
    "examTip": "Pilot Light = only data is running; compute is started on failover. Warm Standby = scaled-down compute is always running.",
    "tags": [
      "DR",
      "RTO",
      "RPO",
      "Architecture"
    ]
  },
  {
    "id": "fc-21",
    "category": "Cost",
    "title": "S3 Lifecycle Transitions",
    "front": "What are the minimum storage duration rules before transitioning objects between S3 storage classes?",
    "back": "• S3 Standard -> S3 Standard-IA / One Zone-IA: 30 days minimum in Standard.\n• S3 Standard-IA -> Glacier Flexible / Instant: 30 days minimum.\n• Objects stored in Glacier Flexible have a 90-day minimum charge; Deep Archive has 180-day minimum charge.",
    "examTip": "Do not transition short-lived temporary objects (<30 days) to IA or Glacier, as early deletion fees apply.",
    "tags": [
      "S3",
      "Lifecycle",
      "Cost"
    ]
  },
  {
    "id": "fc-22",
    "category": "Migration",
    "title": "AWS Snowball vs AWS DataSync",
    "front": "When should you use AWS Snowball Edge vs AWS DataSync for data migration?",
    "back": "• Snowball Edge: Physical appliance shipped via courier for large offline migrations (>10-20 TB up to petabytes) when network bandwidth is constrained (e.g. takes weeks/months over WAN).\n• DataSync: Online network agent for automated, scheduled, encrypted data transfers over Direct Connect or internet (up to 10 Gbps).",
    "examTip": "Rule of thumb: If network transfer time exceeds 1-2 weeks, use Snowball.",
    "tags": [
      "Snowball",
      "DataSync",
      "Migration"
    ]
  },
  {
    "id": "fc-23",
    "category": "Analytics",
    "title": "Amazon Athena vs Amazon Redshift",
    "front": "When should you query data with Amazon Athena vs building a Redshift cluster?",
    "back": "• Athena: Serverless, interactive ad-hoc SQL queries directly on raw S3 data (CSV, JSON, Parquet). Pay only per TB scanned.\n• Redshift: Dedicated cloud data warehouse for complex analytical queries, aggregations, enterprise BI reporting, and massive parallel processing (MPP).",
    "examTip": "Use Athena for infrequent log analysis on S3. Use Redshift for high-concurrency continuous BI dashboards.",
    "tags": [
      "Athena",
      "Redshift",
      "Analytics"
    ]
  },
  {
    "id": "fc-24",
    "category": "Fundamentals",
    "title": "AWS Shared Responsibility Model",
    "front": "In the Shared Responsibility Model, what is AWS responsible for vs the Customer for Amazon RDS?",
    "back": "• AWS: Hardware, host OS, hypervisor, automated database engine patching, storage replication, power, and physical security.\n• Customer: Database network security (Security Groups), database user credentials, table schemas, query optimization, and data encryption settings.",
    "examTip": "For EC2, customer patches the OS. For RDS, AWS patches the OS and database engine.",
    "tags": [
      "Fundamentals",
      "Shared Responsibility",
      "Security"
    ]
  },
  {
    "id": "fc-md-101",
    "category": "Compute",
    "title": "What is the purpose of a cooldown period in Aut...",
    "front": "What is the purpose of a cooldown period in Auto Scaling?",
    "back": "Prevents rapid scaling events by suppressing additional scale-out actions until the cooldown period ends, allowing metrics to stabilize.",
    "examTip": "Key SAA-C03 concept for Compute.",
    "tags": [
      "Compute"
    ]
  },
  {
    "id": "fc-md-102",
    "category": "Compute",
    "title": "Which load balancers support dynamic port mappi...",
    "front": "Which load balancers support dynamic port mapping for ECS?",
    "back": "Application Load Balancer (ALB) and Network Load Balancer (NLB).",
    "examTip": "Key SAA-C03 concept for Compute.",
    "tags": [
      "Compute"
    ]
  },
  {
    "id": "fc-md-103",
    "category": "Compute",
    "title": "How do you prevent instance replacement during ...",
    "front": "How do you prevent instance replacement during maintenance in an ASG?",
    "back": "Put the instance in Standby state, perform maintenance, then return to InService.",
    "examTip": "Key SAA-C03 concept for Compute.",
    "tags": [
      "Compute"
    ]
  },
  {
    "id": "fc-md-104",
    "category": "Storage",
    "title": "What is Amazon S3's consistency model?",
    "front": "What is Amazon S3's consistency model?",
    "back": "Strong read-after-write consistency for all operations (PUTs, DELETEs, LIST).",
    "examTip": "Key SAA-C03 concept for Storage.",
    "tags": [
      "Storage"
    ]
  },
  {
    "id": "fc-md-105",
    "category": "Storage",
    "title": "How do you enable WORM (Write Once Read Many) i...",
    "front": "How do you enable WORM (Write Once Read Many) in S3?",
    "back": "Enable S3 Object Lock at bucket creation (requires versioning).",
    "examTip": "Key SAA-C03 concept for Storage.",
    "tags": [
      "Storage"
    ]
  },
  {
    "id": "fc-md-106",
    "category": "Storage",
    "title": "What's the difference between S3 signed URLs an...",
    "front": "What's the difference between S3 signed URLs and signed cookies?",
    "back": "Signed URLs grant access to individual objects; Signed cookies grant access to multiple objects without changing URLs.",
    "examTip": "Key SAA-C03 concept for Storage.",
    "tags": [
      "Storage"
    ]
  },
  {
    "id": "fc-md-107",
    "category": "Storage",
    "title": "Can you attach an EBS volume across Availabilit...",
    "front": "Can you attach an EBS volume across Availability Zones?",
    "back": "No. Create a snapshot, then restore in the target AZ.",
    "examTip": "Key SAA-C03 concept for Storage.",
    "tags": [
      "Storage"
    ]
  },
  {
    "id": "fc-md-108",
    "category": "Networking",
    "title": "What are the two types of VPC endpoints?",
    "front": "What are the two types of VPC endpoints?",
    "back": "Gateway endpoints (S3, DynamoDB - free) and Interface endpoints (PrivateLink - charged).",
    "examTip": "Key SAA-C03 concept for Networking.",
    "tags": [
      "Networking"
    ]
  },
  {
    "id": "fc-md-109",
    "category": "Networking",
    "title": "What's the difference between Security Groups a...",
    "front": "What's the difference between Security Groups and NACLs?",
    "back": "SGs are stateful, allow-only rules at instance level. NACLs are stateless, allow/deny rules at subnet level.",
    "examTip": "Key SAA-C03 concept for Networking.",
    "tags": [
      "Networking"
    ]
  },
  {
    "id": "fc-md-110",
    "category": "Networking",
    "title": "What placement group type minimizes latency for...",
    "front": "What placement group type minimizes latency for HPC?",
    "back": "Cluster placement group (single AZ, packed instances).",
    "examTip": "Key SAA-C03 concept for Networking.",
    "tags": [
      "Networking"
    ]
  },
  {
    "id": "fc-md-111",
    "category": "Database",
    "title": "What's the difference between Multi-AZ and Read...",
    "front": "What's the difference between Multi-AZ and Read Replicas?",
    "back": "Multi-AZ provides high availability with automatic failover (standby not readable). Read Replicas scale read traffic.",
    "examTip": "Key SAA-C03 concept for Database.",
    "tags": [
      "Database"
    ]
  },
  {
    "id": "fc-md-112",
    "category": "Database",
    "title": "How does Aurora Serverless scale?",
    "front": "How does Aurora Serverless scale?",
    "back": "Automatically adjusts capacity using ACUs (Aurora Capacity Units) based on demand.",
    "examTip": "Key SAA-C03 concept for Database.",
    "tags": [
      "Database"
    ]
  },
  {
    "id": "fc-md-113",
    "category": "Database",
    "title": "Which RDS feature requires versioning?",
    "front": "Which RDS feature requires versioning?",
    "back": "Cross-Region Read Replicas promotion preserves version info.",
    "examTip": "Key SAA-C03 concept for Database.",
    "tags": [
      "Database"
    ]
  },
  {
    "id": "fc-md-114",
    "category": "Compute",
    "title": "What IAM permissions does Lambda need for Cloud...",
    "front": "What IAM permissions does Lambda need for CloudWatch Logs?",
    "back": "logs:CreateLogGroup, logs:CreateLogStream, logs:PutLogEvents.",
    "examTip": "Key SAA-C03 concept for Compute.",
    "tags": [
      "Compute"
    ]
  },
  {
    "id": "fc-md-115",
    "category": "Compute",
    "title": "What ECS networking mode provides task-level se...",
    "front": "What ECS networking mode provides task-level security groups?",
    "back": "awsvpc networking mode.",
    "examTip": "Key SAA-C03 concept for Compute.",
    "tags": [
      "Compute"
    ]
  },
  {
    "id": "fc-md-116",
    "category": "Compute",
    "title": "Where does ECS on AWS Outposts provide lowest l...",
    "front": "Where does ECS on AWS Outposts provide lowest latency?",
    "back": "On-premises, using ECS EC2 launch type.",
    "examTip": "Key SAA-C03 concept for Compute.",
    "tags": [
      "Compute"
    ]
  },
  {
    "id": "fc-md-117",
    "category": "Analytics",
    "title": "Which service analyzes S3 data without a data w...",
    "front": "Which service analyzes S3 data without a data warehouse?",
    "back": "Amazon Athena (serverless SQL queries on S3).",
    "examTip": "Key SAA-C03 concept for Analytics.",
    "tags": [
      "Analytics"
    ]
  },
  {
    "id": "fc-md-118",
    "category": "Analytics",
    "title": "What service creates searchable text from scann...",
    "front": "What service creates searchable text from scanned documents?",
    "back": "Amazon Textract (OCR for forms, tables, handwriting).",
    "examTip": "Key SAA-C03 concept for Analytics.",
    "tags": [
      "Analytics"
    ]
  },
  {
    "id": "fc-md-119",
    "category": "Analytics",
    "title": "Which service converts text to speech?",
    "front": "Which service converts text to speech?",
    "back": "Amazon Polly (Neural TTS, multiple voices/languages).",
    "examTip": "Key SAA-C03 concept for Analytics.",
    "tags": [
      "Analytics"
    ]
  },
  {
    "id": "fc-md-120",
    "category": "Security",
    "title": "What service provides distributed tracing for s...",
    "front": "What service provides distributed tracing for serverless apps?",
    "back": "AWS X-Ray (with Insights for anomaly detection).",
    "examTip": "Key SAA-C03 concept for Security.",
    "tags": [
      "Security"
    ]
  },
  {
    "id": "fc-md-121",
    "category": "Security",
    "title": "How do you rotate API keys automatically?",
    "front": "How do you rotate API keys automatically?",
    "back": "AWS Secrets Manager with custom Lambda rotation function.",
    "examTip": "Key SAA-C03 concept for Security.",
    "tags": [
      "Security"
    ]
  },
  {
    "id": "fc-md-122",
    "category": "Security",
    "title": "What detects underutilized EC2 instances?",
    "front": "What detects underutilized EC2 instances?",
    "back": "AWS Trusted Advisor and CloudWatch metrics.",
    "examTip": "Key SAA-C03 concept for Security.",
    "tags": [
      "Security"
    ]
  },
  {
    "id": "fc-md-123",
    "category": "Migration",
    "title": "Which Storage Gateway type stores data as S3 ob...",
    "front": "Which Storage Gateway type stores data as S3 objects?",
    "back": "S3 File Gateway (SMB/NFS interface, S3 backend).",
    "examTip": "Key SAA-C03 concept for Migration.",
    "tags": [
      "Migration"
    ]
  },
  {
    "id": "fc-md-124",
    "category": "Migration",
    "title": "How do you transfer Lustre data to S3?",
    "front": "How do you transfer Lustre data to S3?",
    "back": "AWS DataSync or FSx for Lustre data repository tasks.",
    "examTip": "Key SAA-C03 concept for Migration.",
    "tags": [
      "Migration"
    ]
  },
  {
    "id": "fc-md-125",
    "category": "Architecture",
    "title": "How do you ensure immediate S3 object availabil...",
    "front": "How do you ensure immediate S3 object availability globally?",
    "back": "S3 provides strong consistency; objects are immediately available after successful PUT.",
    "examTip": "Key SAA-C03 concept for Architecture.",
    "tags": [
      "Architecture"
    ]
  },
  {
    "id": "fc-md-126",
    "category": "Architecture",
    "title": "What's the most cost-effective caching solution?",
    "front": "What's the most cost-effective caching solution?",
    "back": "Amazon ElastiCache (Redis/Memcached for database query caching).",
    "examTip": "Key SAA-C03 concept for Architecture.",
    "tags": [
      "Architecture"
    ]
  },
  {
    "id": "fc-md-127",
    "category": "Architecture",
    "title": "How do you distribute traffic across AZs evenly?",
    "front": "How do you distribute traffic across AZs evenly?",
    "back": "Enable AZ rebalancing with target tracking scaling policy.",
    "examTip": "Key SAA-C03 concept for Architecture.",
    "tags": [
      "Architecture"
    ]
  }
];
