// -------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED by scripts/generate-modules-meta.ts
// DO NOT EDIT MANUALLY. Source of truth is in docs/ directory.
// Run "bun run data:generate" to re-generate this file.
// -------------------------------------------------------------------------

import { ModuleMeta } from '../types';

export const MODULES_METADATA: ModuleMeta[] = [
  {
    "id": "01-AWS-Fundamentals",
    "slug": "01-aws-fundamentals",
    "number": 1,
    "title": "AWS Fundamentals",
    "domain": "Fundamentals",
    "icon": "IconCloud",
    "examWeight": "~10%",
    "timeEstimates": {
      "deepDive": "30 min",
      "fastLearn": "20 min",
      "ultraFast": "5 min"
    },
    "priority": "CRITICAL"
  },
  {
    "id": "02-IAM",
    "slug": "02-iam",
    "number": 2,
    "title": "Identity and Access Management (IAM)",
    "domain": "Security",
    "icon": "IconUserShield",
    "examWeight": "~15-20%",
    "timeEstimates": {
      "deepDive": "30 min",
      "fastLearn": "20 min",
      "ultraFast": "5 min"
    },
    "priority": "CRITICAL"
  },
  {
    "id": "03-Compute",
    "slug": "03-compute",
    "number": 3,
    "title": "Compute Services",
    "domain": "Compute",
    "icon": "IconCpu",
    "examWeight": "~20-25%",
    "timeEstimates": {
      "deepDive": "30 min",
      "fastLearn": "20 min",
      "ultraFast": "10 min"
    },
    "priority": "CRITICAL"
  },
  {
    "id": "04-Storage",
    "slug": "04-storage",
    "number": 4,
    "title": "Storage Services",
    "domain": "Storage",
    "icon": "IconArchive",
    "examWeight": "~15-20%",
    "timeEstimates": {
      "deepDive": "30 min",
      "fastLearn": "20 min",
      "ultraFast": "10 min"
    },
    "priority": "CRITICAL"
  },
  {
    "id": "05-Database",
    "slug": "05-database",
    "number": 5,
    "title": "Database Services",
    "domain": "Database",
    "icon": "IconDatabase",
    "examWeight": "~15-20%",
    "timeEstimates": {
      "deepDive": "30 min",
      "fastLearn": "20 min",
      "ultraFast": "10 min"
    },
    "priority": "CRITICAL"
  },
  {
    "id": "06-Networking",
    "slug": "06-networking",
    "number": 6,
    "title": "Networking & Content Delivery",
    "domain": "Networking",
    "icon": "IconTopologyStar",
    "examWeight": "~20-25%",
    "timeEstimates": {
      "deepDive": "30 min",
      "fastLearn": "20 min",
      "ultraFast": "10 min"
    },
    "priority": "CRITICAL"
  },
  {
    "id": "07-Security",
    "slug": "07-security",
    "number": 7,
    "title": "Security & Compliance",
    "domain": "Security",
    "icon": "IconShieldLock",
    "examWeight": "~20-25%",
    "timeEstimates": {
      "deepDive": "30 min",
      "fastLearn": "20 min",
      "ultraFast": "10 min"
    },
    "priority": "CRITICAL"
  },
  {
    "id": "08-Application-Integration",
    "slug": "08-application-integration",
    "number": 8,
    "title": "Application Integration",
    "domain": "Integration",
    "icon": "IconArrowsJoin",
    "examWeight": "~10-15%",
    "timeEstimates": {
      "deepDive": "30 min",
      "fastLearn": "20 min",
      "ultraFast": "10 min"
    },
    "priority": "HIGH"
  },
  {
    "id": "09-Monitoring",
    "slug": "09-monitoring",
    "number": 9,
    "title": "Monitoring & Management",
    "domain": "Management",
    "icon": "IconChartLine",
    "examWeight": "~10-15%",
    "timeEstimates": {
      "deepDive": "30 min",
      "fastLearn": "20 min",
      "ultraFast": "10 min"
    },
    "priority": "HIGH"
  },
  {
    "id": "10-Migration",
    "slug": "10-migration",
    "number": 10,
    "title": "Migration & Transfer Services",
    "domain": "Migration",
    "icon": "IconTruckDelivery",
    "examWeight": "~8-12%",
    "timeEstimates": {
      "deepDive": "45 min",
      "fastLearn": "20 min",
      "ultraFast": "10 min"
    },
    "priority": "MEDIUM"
  },
  {
    "id": "11-Analytics",
    "slug": "11-analytics",
    "number": 11,
    "title": "Analytics Services",
    "domain": "Analytics",
    "icon": "IconChartHistogram",
    "examWeight": "~8-12%",
    "timeEstimates": {
      "deepDive": "45 min",
      "fastLearn": "20 min",
      "ultraFast": "10 min"
    },
    "priority": "MEDIUM"
  },
  {
    "id": "12-Architecture-Patterns",
    "slug": "12-architecture-patterns",
    "number": 12,
    "title": "Architecture Patterns",
    "domain": "Architecture",
    "icon": "IconHierarchy3",
    "examWeight": "~25-30%",
    "timeEstimates": {
      "deepDive": "30 min",
      "fastLearn": "20 min",
      "ultraFast": "10 min"
    },
    "priority": "CRITICAL"
  },
  {
    "id": "13-Cost-Optimization",
    "slug": "13-cost-optimization",
    "number": 13,
    "title": "Cost Optimization",
    "domain": "Cost",
    "icon": "IconCoin",
    "examWeight": "~10-15%",
    "timeEstimates": {
      "deepDive": "45 min",
      "fastLearn": "20 min",
      "ultraFast": "15 min"
    },
    "priority": "HIGH"
  },
  {
    "id": "14-Practice",
    "slug": "14-practice",
    "number": 14,
    "title": "Practice",
    "domain": "Practice",
    "icon": "IconClipboardCheck",
    "examWeight": "Final Prep",
    "timeEstimates": {
      "deepDive": "30 min",
      "fastLearn": "20 min",
      "ultraFast": "15 min"
    },
    "priority": "CRITICAL"
  }
];
